# Default parameters for ABM
model:
  steps: 200
  n_researchers: 40
  n_policymakers: 10
  n_endusers: 30
  funding_rdte: 1.0         # normalized budget share for RDT&E
  funding_om: 0.5           # normalized budget share for O&M/Procurement
  oversight_regime: linear  # linear | adaptive
  shock_at: 80              # tick when shock is injected (if scenario=shock)
  seed: 42

agents:
  researcher:
    prototype_rate: 0.05      # prob per step to attempt a prototype
    learning_rate: 0.1
    network_degree: 3         # for collaboration
  policymaker:
    allocation_agility: 0.1   # higher = more responsive funding shifts
    oversight_rigidity: 0.8   # higher = more milestones & drag
  enduser:
    adoption_threshold: 0.6   # perceived utility threshold
    feedback_strength: 0.4    # influence on policymakers

# Data sources
data:
  # Relative paths so the repo is self-contained (commit these CSVs under data/)
  labs_locations_csv: data/dod_labs_collaboration_hubs_locations.csv
  rdte_fy26_csv: data/FY2026_SEC4201_RDTandE_All_Line_Items.csv

penalties:
  # Per-failure penalty applied multiplicatively across selected axes
  per_failure: 0.05
  # Maximum total penalty per axis (0..1)
  max_penalty: 0.3
  # Optional decay applied to counts each run step (0 disables)
  decay: 0.0
  # Optional override of axes used per gate; omit to use defaults
  # axes_by_gate:
  #   funding: [researcher, funding_source, org_type]
  #   contracting: [researcher, org_type]
  #   test: [researcher, domain, kinetic_category]
  #   legal: [researcher, authority, domain, kinetic_category]
  #   adoption: [researcher, domain]

gates:
  # Base probabilities and adjustments; tweak to calibrate behavior
  funding_base_linear_early: 0.25
  funding_base_linear_late: 0.20
  funding_base_adaptive_early: 0.40
  funding_base_adaptive_late: 0.35
  funding_base_shock_early: 0.15
  funding_base_shock_late: 0.10
  funding_base_postshock_early: 0.35
  funding_base_postshock_late: 0.30
  color_weight_late_mix: 0.5   # mix of rdte and om for late stages

  test_base:
    feasibility: 0.70
    prototype_demo: 0.65
    functional_test: 0.60
    vulnerability_test: 0.55
    operational_test: 0.50
  test_trl_bonus_per_level: 0.03  # up to ~0.2 cap
  test_trl_bonus_cap: 0.20
  test_kinetic_penalty: 0.05
  test_cyber_vuln_ops_penalty: 0.05
  test_adaptive_bonus: 0.03
  test_shock_penalty: 0.05

  legal_dist:
    favorable: 0.60
    favorable_with_caveats: 0.25
    unfavorable: 0.10
    not_conducted: 0.05
  legal_title50_shift: 0.10  # shifts from favorable → caveats/unfavorable
  legal_kinetic_shift: 0.05
  legal_penalty_shift_cap: 0.50

  contracting_base:
    GovLab: 0.60
    GovContractor: 0.55
    Commercial: 0.50
  contracting_adaptive_bonus: 0.10
  contracting_linear_commercial_penalty: 0.05
